### ISSUE TITLE
Is username password and certificate configured? brother

### ISSUE THREAD

**Issue by kuaile-zc** [TeslaCN/camel-rocketmq#2]
Brother. Whether the rocket supports accessKey  and secretKey?

**Comment by TeslaCN** [comment]
Not supported.

**Comment by kuaile-zc** [comment]
I wanted to look at the code and support it。

发自我的iPhone


------------------ Original ------------------
From: 吴伟杰 ***@***.***&gt;
Date: Mon,May 30,2022 10:30 AM
To: TeslaCN/camel-rocketmq ***@***.***&gt;
Cc: Corey ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TeslaCN/camel-rocketmq] Is username password and certificate configured? brother (Issue #2)





 
Not supported.

**Comment by TeslaCN** [comment]
I think it won't be hard.

**Comment by kuaile-zc** [comment]
> I think it won't be hard.

你好，我提交了一个pr麻烦您查看一下。
https://github.com/TeslaCN/camel-rocketmq/pull/3

**Comment by TeslaCN** [comment]
Close via #3.
